name: Build

on:
  push:
    paths-ignore:
      - '*.md'

  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '*.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Required by GitVersion
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Build Plugin
        run: dotnet build --configuration Release
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true

      - name: Checkout Repository (Dalamud.Divination.Template)
        uses: actions/checkout@v2
        with:
          repository: SlashNephy/Dalamud.Divination.Template
          path: template
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          # Required by GitVersion
          fetch-depth: 0

      - name: Update Submodule
        working-directory: template
        run: |
          git submodule foreach git pull origin master
          git submodule foreach git checkout master

      - name: Push Template
        uses: EndBug/add-and-commit@v7
        with:
          cwd: template
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: Update Common
