name: Build

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '*.md'

jobs:
  check:
    runs-on: windows-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # Required by GitVersion
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Build Plugin
        run: dotnet build --configuration Release
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true

      - name: Checkout Plugin Repository
        uses: actions/checkout@v2
        with:
          path: repo
          repository: SlashNephy/Dalamud.DivinationPluginRepo

      - name: Copy into Plugin Repository (stable)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: Copy-Item ${{ secrets.PLUGIN_PROJECT_NAME }}\bin\Release\${{ secrets.PLUGIN_PROJECT_NAME }} repo\dist\stable -Recurse
      - name: Copy into Plugin Repository (testing)
        if: github.event_name == 'push' && github.ref != 'refs/heads/master'
        run: Copy-Item ${{ secrets.PLUGIN_PROJECT_NAME }}\bin\Release\${{ secrets.PLUGIN_PROJECT_NAME }} repo\dist\testing -Recurse

      - name: Push to Plugin Repository
        uses: EndBug/add-and-commit@v7
        with:
          cwd: repo
          add: --all
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: Update ${{ secrets.PLUGIN_PROJECT_NAME }}
