name: Check

on:
  push:
    paths-ignore:
      - '*.md'

  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '*.md'

  workflow_dispatch:

jobs:
  check:
    runs-on: windows-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # Required by GitVersion
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Build Plugin
        run: dotnet build --configuration Release
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Plugin
          path: ${{ secrets.PLUGIN_PROJECT_NAME }}\bin\Release\${{ secrets.PLUGIN_PROJECT_NAME }}
          if-no-files-found: error
