name: 'CI (AetheryteLinkInChat)'

on:
  push:
    paths:
      - 'AetheryteLinkInChat/**'
      - 'Common/**'
  pull_request:
    paths:
      - 'AetheryteLinkInChat/**'
      - 'Common/**'
    types:
      - opened
      - synchronize
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    uses: SlashNephy/Divination/.github/workflows/reusable-build-plugin.yml@master
    with:
      plugin-name: 'AetheryteLinkInChat'
      working-directory: 'AetheryteLinkInChat'
    permissions:
      contents: read
      actions: write

  deploy:
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
    needs: build
    uses: SlashNephy/Divination/.github/workflows/reusable-deploy-plugin.yml@master
    with:
      plugin-name: 'AetheryteLinkInChat'
    secrets:
      DEPLOY_GITHUB_TOKEN: '${{ secrets.DEPLOY_GITHUB_TOKEN }}'
    permissions:
      actions: read
