name: 'CI (InstanceIDViewer)'

on:
  push:
    paths:
      - 'InstanceIDViewer/**'
    branches:
      - 'master'

  pull_request:
    paths:
      - 'InstanceIDViewer/**'
    types:
      - opened
      - synchronize

  release:
    types:
      - created

  workflow_dispatch:

jobs:
  build:
    uses: SlashNephy/Divination/.github/workflows/reusable-build-plugin.yml@master
    with:
      plugin-name: 'InstanceIDViewer'
      working-directory: 'InstanceIDViewer'
    permissions:
      contents: read
      actions: write

  deploy:
    if: github.event_name != 'pull_request'
    needs: build
    uses: SlashNephy/Divination/.github/workflows/reusable-deploy-plugin.yml@master
    with:
      plugin-name: 'InstanceIDViewer'
    secrets:
      DEPLOY_GITHUB_TOKEN: '${{ secrets.DEPLOY_GITHUB_TOKEN }}'
    permissions:
      actions: read
